spring.application.name=PeerTubeMiner

# Añadidas todas las líneas que aparecen en el vídeo, pueden no ser necesarias
server.port=8081
logging.level.aiss.peertubeminer.controller=DEBUG
peertubeminer.baseuri=https://peertube.tv/api/v1

peertubeminer.maxVideos = 10
peertubeminer.maxComments = 2

videominer.uri=http://localhost:8080/videominer/channels